// Code generated by command: go run main.go -stubs ./stubs_avo.go -out ./distance_avo.s. DO NOT EDIT.

package distance

// SquaredEuclideanFloat16AVX2 calcola la distanza euclidea al quadrato per vettori float16 (rappresentati come uint16) usando AVX2.
//
//go:noescape
func SquaredEuclideanFloat16AVX2(v1 []uint16, v2 []uint16) float32
