// Code generated by command: go run main.go -stubs ./stubs_avo_amd64.go -out ./distance_avo_amd64.s. DO NOT EDIT.

package distance

// SquaredEuclideanFloat16AVX2 calculates the squared Euclidean distance for float16 vectors (represented as uint16) using AVX2.
//
//go:noescape
func SquaredEuclideanFloat16AVX2(v1 []uint16, v2 []uint16) float32
