// Package cognitive provides autonomous background processes for memory consolidation,
// contradiction detection, and meta-knowledge generation (Reflection Engine).
package cognitive

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"math"
	"strings"
	"time"

	"github.com/sanonone/kektordb/pkg/core"
	"github.com/sanonone/kektordb/pkg/engine"
	"github.com/sanonone/kektordb/pkg/llm"
)

// ReflectionType categorizes the insights generated by the Gardener.
type ReflectionType string

const (
	TypeConsolidation ReflectionType = "consolidation" // Merged redundant memories
	TypeContradiction ReflectionType = "contradiction" // Detected conflicting facts
	TypeImportance    ReflectionType = "importance"    // Importance shift
)

// Reflection defines the schema for a meta-memory node.
// These will be stored in the DB with kind="reflection" and linked to original memories.
type Reflection struct {
	Type        ReflectionType `json:"type"`
	Content     string         `json:"content"`
	Confidence  float64        `json:"confidence"`
	Status      string         `json:"status"`       // e.g., "resolved", "unresolved"
	DerivedFrom []string       `json:"derived_from"` // Original memory IDs
}

// Config holds the scheduling and AI settings for the cognitive engine.
type Config struct {
	Enabled       bool
	Interval      time.Duration
	Mode          string   // "basic" (No LLM), "advanced" (Uses LLM)
	TargetIndexes []string // ["*"] for all, or["mcp_memory", "tenant_A"]
}

// Gardener is the autonomous background worker that analyzes the database graph
// to consolidate memories and generate reflections.
type Gardener struct {
	eng         *engine.Engine
	llm         llm.Client // LLM client for synthesis and reasoning
	cfg         Config
	stopCh      chan struct{}
	scanCursors map[string]uint32 // Remember where we left off for each Namespace
}

type llmContradictionResponse struct {
	Contradiction       bool   `json:"contradiction"`
	Reason              string `json:"reason"`
	SuggestedResolution string `json:"suggested_resolution"`
	ActionRequired      bool   `json:"action_required"`
}

type llmPreferenceResponse struct {
	PreferencesDiscovered map[string]string `json:"preferences_discovered"`
	Recommendation        string            `json:"recommendation"`
}

type llmFailurePatternResponse struct {
	Pattern        string `json:"pattern"`
	RootCause      string `json:"root_cause"`
	Recommendation string `json:"recommendation"`
	Severity       string `json:"severity"`
}

type llmEvolutionResponse struct {
	Timeline        string   `json:"timeline"`
	CompetencyLevel string   `json:"competency_level"`
	KnowledgeGaps   []string `json:"knowledge_gaps"`
	NextSteps       string   `json:"next_steps"`
}

// NewGardener initializes the cognitive engine.
func NewGardener(eng *engine.Engine, llmClient llm.Client, cfg Config) *Gardener {
	if cfg.Interval == 0 {
		cfg.Interval = 10 * time.Minute // Default: think every 10 minutes
	}
	return &Gardener{
		eng:         eng,
		llm:         llmClient,
		cfg:         cfg,
		stopCh:      make(chan struct{}),
		scanCursors: make(map[string]uint32),
	}
}

// Start launches the Gardener's background loop.
func (g *Gardener) Start() {
	if !g.cfg.Enabled {
		return
	}
	slog.Info("[Cognitive Engine] Gardener started. Sleep cycle initiated.", "interval", g.cfg.Interval)
	go g.loop()
}

// Stop gracefully halts the cognitive engine.
func (g *Gardener) Stop() {
	if !g.cfg.Enabled {
		return
	}
	close(g.stopCh)
	slog.Info("[Cognitive Engine] Gardener stopped.")
}

func (g *Gardener) loop() {
	ticker := time.NewTicker(g.cfg.Interval)
	defer ticker.Stop()

	for {
		select {
		case <-g.stopCh:
			return
		case <-ticker.C:
			g.think()
		}
	}
}

// isIndexAllowed checks whether this index is in the Gardener's target list.
func (c *Config) isIndexAllowed(indexName string) bool {
	if len(c.TargetIndexes) == 0 {
		return false
	}
	for _, target := range c.TargetIndexes {
		if target == "*" || target == indexName {
			return true
		}
	}
	return false
}

// think is the main entry point for the "REM Sleep" phase of the database.
func (g *Gardener) think() {
	slog.Info("[Cognitive Engine] Gardener is waking up... scanning all active namespaces.")

	indexInfos, err := g.eng.DB.GetVectorIndexInfoAPI()
	if err != nil || len(indexInfos) == 0 {
		return
	}

	for _, info := range indexInfos {
		idx := info.Name

		// 1. Skip indexes not in the target list.
		if !g.cfg.isIndexAllowed(idx) {
			continue
		}

		// 2. Skip indexes with too few vectors to produce meaningful clusters.
		if info.VectorCount < 10 {
			continue
		}

		slog.Debug("[Cognitive Engine] Analyzing namespace", "index", idx, "mode", g.cfg.Mode)

		// =====================================================================
		// LAYER 1: BASIC (Fast, Math & Graph Only, NO LLM)
		// Always active when enabled. CPU cost: low.
		// =====================================================================

		g.detectKnowledgeGaps(idx)
		g.detectImportanceShifts(idx)
		g.detectSentimentShifts(idx, info.TextLanguage)
		g.detectCentralityShifts(idx)
		g.detectForgettingPatterns(idx)

		// Consolidation: cluster finding is pure math (no LLM needed).
		clusters := g.findRedundantClusters(idx, 0.90, 5)
		for _, cluster := range clusters {
			g.consolidateCluster(idx, cluster) // LLM used if available, deterministic fallback otherwise.
		}

		// Advanced-only: contradiction detection (requires LLM).
		if g.llm != nil && (g.cfg.Mode == "advanced" || g.cfg.Mode == "meta") {
			g.detectContradictions(idx)
			g.detectUserPreferences(idx)
			g.detectRepeatedFailures(idx)
			g.detectKnowledgeEvolution(idx)
		}
	}

	slog.Info("[Cognitive Engine] Sleep cycle completed. Graph optimized.")

}

// MemoryCluster represents a group of highly similar memories.
type MemoryCluster struct {
	CenterID  string
	MemberIDs []string
}

func (g *Gardener) findRedundantClusters(indexName string, similarityThreshold float64, minClusterSize int) []MemoryCluster {
	currentCursor := g.scanCursors[indexName]

	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 500)
	if err != nil || len(ids) == 0 {
		return nil
	}
	g.scanCursors[indexName] = nextCursor

	vectorDataList, err := g.eng.VGetMany(indexName, ids)
	if err != nil {
		return nil
	}

	var clusters []MemoryCluster
	clusteredSet := make(map[string]struct{})

	for _, vData := range vectorDataList {
		if _, alreadyClustered := clusteredSet[vData.ID]; alreadyClustered {
			continue
		}

		// Skip archived memories and meta-nodes (master/reflections).
		if archived, ok := vData.Metadata["_archived"].(bool); ok && archived {
			continue
		}
		if memType, ok := vData.Metadata["type"].(string); ok && (memType == "consolidated_memory" || memType == "reflection") {
			continue
		}

		results, err := g.eng.VSearchWithScores(indexName, vData.Vector, 10)
		if err != nil {
			continue
		}

		var currentCluster []string
		for _, res := range results {
			if res.Score >= similarityThreshold {
				if _, seen := clusteredSet[res.ID]; !seen {
					// Also skip archived or meta-type neighbors.
					neighborData, err := g.eng.VGet(indexName, res.ID)
					if err == nil {
						if arch, ok := neighborData.Metadata["_archived"].(bool); ok && arch {
							continue
						}
						if memType, ok := neighborData.Metadata["type"].(string); ok && (memType == "consolidated_memory" || memType == "reflection") {
							continue
						}

						currentCluster = append(currentCluster, res.ID)
						clusteredSet[res.ID] = struct{}{}
					}
				}
			}
		}

		if len(currentCluster) >= minClusterSize {
			clusters = append(clusters, MemoryCluster{
				CenterID:  vData.ID,
				MemberIDs: currentCluster,
			})
		}
	}

	return clusters
}

// consolidateCluster sends redundant memories to the LLM for synthesis, creates a Master Memory,
// and archives the original memories by linking them via the graph.
func (g *Gardener) consolidateCluster(indexName string, cluster MemoryCluster) {
	// 1. Fetch data for all memories in the cluster
	items, err := g.eng.VGetMany(indexName, cluster.MemberIDs)
	if err != nil || len(items) == 0 {
		return
	}

	// 2. Prepare text and compute the Average Vector (Zero-Cost Embedding!)
	var texts []string
	dim := len(items[0].Vector)
	avgVector := make([]float32, dim)

	maxItemsForLLM := 15

	for i, item := range items {
		content := ""
		if val, ok := item.Metadata["content"]; ok {
			content = fmt.Sprintf("%v", val)
		}

		if i < maxItemsForLLM {
			texts = append(texts, fmt.Sprintf("- %s", content))
		}

		// Sum all vectors in the cluster (not just the LLM subset) to compute a precise average.
		if len(item.Vector) == dim {
			for j, v := range item.Vector {
				avgVector[j] += v
			}
		}
	}

	// Vector Average
	for i := range avgVector {
		avgVector[i] /= float32(len(items))
	}

	// 3. Synthesis: LLM if available, otherwise deterministic fallback.
	var summary string
	if g.llm != nil {
		sysPrompt := "You are a cognitive memory consolidator for an AI agent. Read the following redundant memory snippets and synthesize them into a single, comprehensive, and clear memory/fact. Keep it concise but retain all key information. Return ONLY the synthesized text, nothing else."
		userPrompt := strings.Join(texts, "\n")

		slog.Info("[Cognitive Engine] Asking LLM to synthesize memories...", "cluster_size", len(items))

		summary, err = g.llm.Chat(sysPrompt, userPrompt)
		if err != nil || summary == "" {
			slog.Warn("[Cognitive Engine] LLM synthesis failed", "error", err)
			return
		}
		summary = strings.TrimSpace(strings.TrimPrefix(strings.TrimSuffix(summary, "```"), "```"))
	} else {
		// Deterministic fallback: pick the most graph-central member as master.
		slog.Info("[Cognitive Engine] No LLM available. Using most graph-central member as master.", "cluster_size", len(items))
		summary = g.pickCentralContent(indexName, items)
		if summary == "" {
			return
		}
	}

	// 4. Save Master Memory to DB
	masterID := fmt.Sprintf("consolidation_%d", time.Now().UnixNano())
	masterMeta := map[string]any{
		"content":            summary,
		"type":               "consolidated_memory",
		"_created_at":        float64(time.Now().Unix()),
		"derived_from_count": float64(len(items)),
	}

	err = g.eng.VAdd(indexName, masterID, avgVector, masterMeta)
	if err != nil {
		slog.Error("[Cognitive Engine] Failed to save master memory", "error", err)
		return
	}

	// 5. Transfer external graph edges from old memories to the master node.
	clusterSet := make(map[string]struct{})
	for _, item := range items {
		clusterSet[item.ID] = struct{}{}
	}

	skipEdges := map[string]bool{
		"consolidated_into":    true,
		"derived_from":         true,
		"analyzed_against":     true,
		"gap_analyzed":         true,
		"sentiment_analyzed":   true,
		"centrality_analyzed":  true,
		"decay_analyzed":       true,
		"suggests_link":        true,
		"contradicts":          true,
		"contradicted_by":      true,
		"focus_shifted":        true,
		"focus_shifted_by":     true,
		"sentiment_shift":      true,
		"sentiment_shifted_by": true,
		"became_central":       true,
		"centralized_by":       true,
		"knowledge_decay":      true,
		"decaying_in":          true,
	}

	for _, item := range items {
		oldID := item.ID

		// A. Outgoing edges (master -> target)
		outRels := g.eng.VGetRelations(indexName, oldID)
		for relType := range outRels {
			if skipEdges[relType] {
				continue
			}
			edges, found := g.eng.VGetEdges(indexName, oldID, relType, 0)
			if !found {
				continue
			}
			for _, edge := range edges {
				if _, inCluster := clusterSet[edge.TargetID]; inCluster {
					continue
				}
				if err := g.eng.VLink(indexName, masterID, edge.TargetID, relType, "", edge.Weight, edge.GetProps()); err != nil {
					slog.Warn("[Cognitive Engine] Failed to transfer outgoing edge", "error", err)
				}
			}
		}

		// B. Incoming edges (source -> master)
		inRels := g.eng.VGetIncomingRelations(indexName, oldID)
		for relType := range inRels {
			if skipEdges[relType] {
				continue
			}
			edges, found := g.eng.VGetIncomingEdges(indexName, oldID, relType, 0)
			if !found {
				continue
			}
			for _, edge := range edges {
				// In VGetIncomingEdges, TargetID is the source node.
				sourceID := edge.TargetID
				if _, inCluster := clusterSet[sourceID]; inCluster {
					continue
				}
				if err := g.eng.VLink(indexName, sourceID, masterID, relType, "", edge.Weight, edge.GetProps()); err != nil {
					slog.Warn("[Cognitive Engine] Failed to transfer incoming edge", "error", err)
				}
			}
		}
	}

	// 6. Archive old memories
	for _, item := range items {
		// Link: old memory --[consolidated_into]--> master memory
		if err := g.eng.VLink(indexName, item.ID, masterID, "consolidated_into", "derived_from", 1.0, nil); err != nil {
			slog.Warn("[Cognitive Engine] Failed to link consolidated memory", "from", item.ID, "error", err)
		}

		metaUpdate := map[string]any{
			"_archived":          true,
			"_consolidated_into": masterID,
		}
		if err := g.eng.VSetMetadata(indexName, item.ID, metaUpdate); err != nil {
			slog.Warn("[Cognitive Engine] Failed to archive memory", "id", item.ID, "error", err)
		}
	}

	slog.Info("[Cognitive Engine] Cluster successfully consolidated! 🧠",
		"master_id", masterID,
		"merged_count", len(items),
		"summary_preview", summary[:min(50, len(summary))]+"...")
}

// pickCentralContent returns the content of the most graph-connected member in the cluster.
// Used as a deterministic fallback when no LLM is available for synthesis.
func (g *Gardener) pickCentralContent(indexName string, items []core.VectorData) string {
	var bestContent string
	maxDegree := -1
	for _, item := range items {
		outRels := g.eng.VGetRelations(indexName, item.ID)
		inRels := g.eng.VGetIncomingRelations(indexName, item.ID)
		degree := 0
		for _, t := range outRels {
			degree += len(t)
		}
		for _, s := range inRels {
			degree += len(s)
		}
		content, _ := item.Metadata["content"].(string)
		if degree > maxDegree || (degree == maxDegree && len(content) > len(bestContent)) {
			maxDegree = degree
			bestContent = content
		}
	}
	return bestContent
}

// detectContradictions finds memories about the same topic that make conflicting claims.
func (g *Gardener) detectContradictions(indexName string) {
	// Small batch (50) because each pair triggers an LLM call.
	currentCursor := g.scanCursors[indexName+"_contradictions"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 50)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_contradictions"] = nextCursor

	nodes, _ := g.eng.VGetMany(indexName, ids)

	for _, node := range nodes {
		contentA, ok := node.Metadata["content"].(string)
		if !ok || contentA == "" {
			continue
		}

		// Find semantically similar but non-identical memories (score 0.70–0.95).
		neighbors, _ := g.eng.VSearchWithScores(indexName, node.Vector, 5)

		for _, neighbor := range neighbors {
			if neighbor.ID == node.ID || neighbor.Score > 0.95 || neighbor.Score < 0.70 {
				continue
			}

			// Dedup via graph edge: skip if this pair was already analyzed.
			existingLinks, found := g.eng.VGetLinks(indexName, node.ID, "analyzed_against")
			if found {
				skip := false
				for _, link := range existingLinks {
					if link == neighbor.ID {
						skip = true
						break
					}
				}
				if skip {
					continue
				}
			}

			// Mark the pair as analyzed to prevent re-processing.
			if err := g.eng.VLink(indexName, node.ID, neighbor.ID, "analyzed_against", "analyzed_against", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to mark pair as analyzed", "error", err)
				continue
			}

			neighborData, err := g.eng.VGet(indexName, neighbor.ID)
			if err != nil {
				continue
			}
			contentB, ok := neighborData.Metadata["content"].(string)
			if !ok {
				continue
			}

			// Ask the LLM for a contradiction analysis.
			dateA := ""
			if ts, ok := node.Metadata["_created_at"].(float64); ok {
				dateA = time.Unix(int64(ts), 0).Format("2006-01-02")
			}
			dateB := ""
			if ts, ok := neighborData.Metadata["_created_at"].(float64); ok {
				dateB = time.Unix(int64(ts), 0).Format("2006-01-02")
			}

			sysPrompt := `Analyze the following two memory statements from an AI agent.
Consider their timestamps — the more recent memory is likely more accurate.
Do they logically contradict each other?
Return ONLY a valid JSON object:
{"contradiction": true/false, "reason": "...", "suggested_resolution": "...", "action_required": true/false}

Guidelines for action_required:
- true if the agent must manually investigate or choose which memory to keep
- false if the contradiction is minor or can be auto-resolved by preferring the newer memory

Guidelines for suggested_resolution:
- If timestamps differ significantly, suggest: "Keep the newer memory (from <date>) and archive the older one."
- If both are equally recent, suggest: "Verify which statement is correct and discard the other."
- If not a contradiction, set to ""`

			userPrompt := fmt.Sprintf("Memory A (from %s): %s\nMemory B (from %s): %s", dateA, contentA, dateB, contentB)

			respText, err := g.llm.Chat(sysPrompt, userPrompt)
			if err != nil {
				continue
			}

			// Extract JSON from the response, stripping any markdown or extra text.
			startIdx := strings.Index(respText, "{")
			endIdx := strings.LastIndex(respText, "}")
			if startIdx != -1 && endIdx != -1 && endIdx > startIdx {
				respText = respText[startIdx : endIdx+1]
			}

			var aiAnalysis llmContradictionResponse
			if err := json.Unmarshal([]byte(respText), &aiAnalysis); err == nil {
				if aiAnalysis.Contradiction {
					slog.Info("[Cognitive Engine] ⚠️ Contradiction Detected!", "reason", aiAnalysis.Reason)

					reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())

					// Zero-cost embedding: average of the two conflicting vectors.
					dim := len(node.Vector)
					avgVec := make([]float32, dim)
					for i := range node.Vector {
						avgVec[i] = (node.Vector[i] + neighborData.Vector[i]) / 2.0
					}

					meta := map[string]any{
						"type":                 "reflection",
						"content":              fmt.Sprintf("Conflict detected: %s", aiAnalysis.Reason),
						"status":               "unresolved",
						"confidence":           0.7,
						"suggested_resolution": aiAnalysis.SuggestedResolution,
						"action_required":      aiAnalysis.ActionRequired,
						"_created_at":          float64(time.Now().Unix()),
					}

					g.eng.VAdd(indexName, reflectionID, avgVec, meta)

					// Link both memories to the reflection node.
					if err := g.eng.VLink(indexName, reflectionID, node.ID, "contradicts", "contradicted_by", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link contradiction", "error", err)
					}
					if err := g.eng.VLink(indexName, reflectionID, neighbor.ID, "contradicts", "contradicted_by", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link contradiction", "error", err)
					}
				}
			}
		}
	}
}

// detectImportanceShifts detects entities that have suddenly become popular
// by comparing edge timestamps over the last 3 days.
func (g *Gardener) detectImportanceShifts(indexName string) {
	currentCursor := g.scanCursors[indexName+"_shifts"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 200)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_shifts"] = nextCursor

	now := time.Now().UnixNano()
	threeDaysAgo := now - (3 * 24 * int64(time.Hour))

	for _, id := range ids {
		edges, found := g.eng.VGetIncomingEdges(indexName, id, "mentions", 0)
		if !found || len(edges) < 5 {
			continue // Too few links to be significant.
		}

		recentMentions := 0
		oldMentions := 0

		// Count when edges were created (time-travel query).
		for _, edge := range edges {
			if edge.CreatedAt > threeDaysAgo {
				recentMentions++
			} else {
				oldMentions++
			}
		}

		// Spike heuristic: more mentions in the last 3 days than in all prior history.
		if recentMentions > 5 && recentMentions > (oldMentions*2) {
			slog.Info("[Cognitive Engine] 📈 Importance Shift Detected!", "entity", id, "recent_mentions", recentMentions)

			// Anti-spam: skip if a reflection already exists for this entity.
			alreadyFlagged := false
			if existingRefs, ok := g.eng.VGetIncoming(indexName, id, "focus_shifted"); ok {
				if len(existingRefs) > 0 {
					alreadyFlagged = true
				}
			}

			if !alreadyFlagged {
				reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())

				nodeData, _ := g.eng.VGet(indexName, id)

				confidence := math.Min(1.0, float64(recentMentions)/10.0)
				meta := map[string]any{
					"type":        "reflection",
					"content":     fmt.Sprintf("Sudden surge of interest in '%s'. Received %d new mentions recently.", id, recentMentions),
					"status":      "insight",
					"confidence":  confidence,
					"_created_at": float64(time.Now().Unix()),
				}

				g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
				if err := g.eng.VLink(indexName, reflectionID, id, "focus_shifted", "focus_shifted_by", 1.0, nil); err != nil {
					slog.Warn("[Cognitive Engine] Failed to link importance shift", "error", err)
				}
			}
		}
	}
}

// ForceThink triggers a cognitive cycle immediately for a specific index.
// Used by the HTTP API for manual intervention or after heavy bulk imports.
func (g *Gardener) ForceThink(indexName string) {
	if !g.eng.IndexExists(indexName) {
		slog.Warn("[Cognitive Engine] Cannot think on missing index", "index", indexName)
		return
	}

	// Security check: verify index is in the target list.
	if !g.cfg.isIndexAllowed(indexName) {
		slog.Warn("[Cognitive Engine] Index not in target list for cognitive analysis", "index", indexName)
		return
	}

	slog.Info("[Cognitive Engine] Manual reflection cycle triggered.", "index", indexName, "mode", g.cfg.Mode)

	// Look up the index language for sentiment analysis.
	var indexLang string
	if info, err := g.eng.DB.GetSingleVectorIndexInfoAPI(indexName); err == nil {
		indexLang = info.TextLanguage
	}

	// =====================================================================
	// LAYER 1: BASIC (Fast, Math & Graph Only, NO LLM)
	// =====================================================================
	g.detectKnowledgeGaps(indexName)
	g.detectImportanceShifts(indexName)
	g.detectSentimentShifts(indexName, indexLang)
	g.detectCentralityShifts(indexName)
	g.detectForgettingPatterns(indexName)

	// Consolidation: cluster finding is pure math (no LLM needed).
	clusters := g.findRedundantClusters(indexName, 0.90, 5)
	for _, cluster := range clusters {
		g.consolidateCluster(indexName, cluster)
	}

	// Advanced-only: contradiction detection (requires LLM).
	if g.llm != nil && (g.cfg.Mode == "advanced" || g.cfg.Mode == "meta") {
		g.detectContradictions(indexName)
		g.detectUserPreferences(indexName)
		g.detectRepeatedFailures(indexName)
		g.detectKnowledgeEvolution(indexName)
	}
}

// detectKnowledgeGaps finds concepts that are semantically very close but
// lack an explicit topological relationship in the graph.
func (g *Gardener) detectKnowledgeGaps(indexName string) {
	currentCursor := g.scanCursors[indexName+"_gaps"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_gaps"] = nextCursor

	nodes, _ := g.eng.VGetMany(indexName, ids)

	for _, node := range nodes {
		// Only analyze entities and documents; skip raw chunks to reduce noise.
		nodeType, ok := node.Metadata["type"].(string)
		if !ok || (nodeType != "entity" && nodeType != "document") {
			continue
		}

		// Pre-load all relations once (not per neighbor).
		outRels := g.eng.VGetRelations(indexName, node.ID)
		inRels := g.eng.VGetIncomingRelations(indexName, node.ID)

		// Find top-5 semantically similar nodes (score > 0.85).
		neighbors, _ := g.eng.VSearchWithScores(indexName, node.Vector, 5)

		for _, neighbor := range neighbors {
			if neighbor.ID == node.ID || neighbor.Score < 0.85 {
				continue
			}

			neighborData, err := g.eng.VGet(indexName, neighbor.ID)
			if err != nil {
				continue
			}
			nType, ok := neighborData.Metadata["type"].(string)
			if !ok || (nType != "entity" && nType != "document") {
				continue
			}

			// Check if a direct graph edge exists between the two nodes (both directions).
			connected := false

			// Outgoing edges (node -> neighbor)
			for _, targets := range outRels {
				for _, t := range targets {
					if t == neighbor.ID {
						connected = true
						break
					}
				}
				if connected {
					break
				}
			}

			// Incoming edges (neighbor -> node)
			if !connected {
				for _, sources := range inRels {
					for _, s := range sources {
						if s == neighbor.ID {
							connected = true
							break
						}
					}
					if connected {
						break
					}
				}
			}

			// 5. Gap found: semantically close but topologically disconnected.
			if !connected {
				slog.Info("[Cognitive Engine] 🧩 Knowledge Gap Detected!", "node_a", node.ID, "node_b", neighbor.ID)

				// Dedup: check if this pair was already flagged.
				existingLinks, found := g.eng.VGetLinks(indexName, node.ID, "gap_analyzed")
				skip := false
				if found {
					for _, link := range existingLinks {
						if link == neighbor.ID {
							skip = true
							break
						}
					}
				}

				if !skip {
					if err := g.eng.VLink(indexName, node.ID, neighbor.ID, "gap_analyzed", "gap_analyzed", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to mark gap as analyzed", "error", err)
						continue
					}

					reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())

					dim := len(node.Vector)
					avgVec := make([]float32, dim)
					for i := range node.Vector {
						avgVec[i] = (node.Vector[i] + neighborData.Vector[i]) / 2.0
					}

					nameA := node.Metadata["name"]
					if nameA == nil {
						nameA = node.ID
					}
					nameB := neighborData.Metadata["name"]
					if nameB == nil {
						nameB = neighbor.ID
					}

					meta := map[string]any{
						"type":        "reflection",
						"content":     fmt.Sprintf("Implicit relationship discovered: '%v' and '%v' share high semantic similarity (%.2f) but lack an explicit graph connection. Consider linking them.", nameA, nameB, neighbor.Score),
						"status":      "insight",
						"confidence":  neighbor.Score,
						"_created_at": float64(time.Now().Unix()),
					}

					g.eng.VAdd(indexName, reflectionID, avgVec, meta)
					if err := g.eng.VLink(indexName, reflectionID, node.ID, "suggests_link", "", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link knowledge gap", "error", err)
					}
					if err := g.eng.VLink(indexName, reflectionID, neighbor.ID, "suggests_link", "", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link knowledge gap", "error", err)
					}
				}
			}
		}
	}
}

// detectUserPreferences scans recent memories tagged as user interactions
// and uses the LLM to extract structured user preferences.
func (g *Gardener) detectUserPreferences(indexName string) {
	currentCursor := g.scanCursors[indexName+"_preferences"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 200)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_preferences"] = nextCursor

	nodes, _ := g.eng.VGetMany(indexName, ids)

	// Filter for memories tagged as user interactions or observations.
	var relevantIDs []string
	var promptLines []string
	for _, node := range nodes {
		tags, ok := node.Metadata["tags"].([]any)
		if !ok {
			continue
		}
		isRelevant := false
		for _, t := range tags {
			tagStr, _ := t.(string)
			if tagStr == "user_interaction" || tagStr == "observation" {
				isRelevant = true
				break
			}
		}
		if !isRelevant {
			continue
		}

		content, _ := node.Metadata["content"].(string)
		if content == "" {
			continue
		}

		dateStr := ""
		if ts, ok := node.Metadata["_created_at"].(float64); ok {
			dateStr = time.Unix(int64(ts), 0).Format("2006-01-02")
		}

		relevantIDs = append(relevantIDs, node.ID)
		promptLines = append(promptLines, fmt.Sprintf("- [%s] %s", dateStr, content))
	}

	if len(promptLines) < 2 {
		return // Not enough data to extract meaningful preferences.
	}

	sysPrompt := `You are a user behavior analyst for an AI agent. Analyze the following interaction memories and extract structured user preferences.
Return ONLY a valid JSON object:
{"preferences_discovered": {"key": "value", ...}, "recommendation": "..."}

Guidelines:
- Extract behavioral patterns (communication style, time preferences, topic interests).
- Use descriptive keys (e.g., "communication_style", "preferred_meeting_time").
- If no clear preferences emerge, return empty preferences_discovered.
- The recommendation should suggest how the agent should adapt its behavior.`

	userPrompt := "User interaction memories:\n" + strings.Join(promptLines, "\n")

	slog.Info("[Cognitive Engine] Analyzing user preferences...", "memory_count", len(promptLines))

	respText, err := g.llm.Chat(sysPrompt, userPrompt)
	if err != nil {
		return
	}

	// Extract JSON from the response.
	startIdx := strings.Index(respText, "{")
	endIdx := strings.LastIndex(respText, "}")
	if startIdx != -1 && endIdx != -1 && endIdx > startIdx {
		respText = respText[startIdx : endIdx+1]
	}

	var aiResp llmPreferenceResponse
	if err := json.Unmarshal([]byte(respText), &aiResp); err != nil {
		return
	}

	if len(aiResp.PreferencesDiscovered) == 0 {
		return // No preferences found.
	}

	// Create a user_profile_insight node.
	insightID := fmt.Sprintf("user_profile_%d", time.Now().UnixNano())

	// Use the first source memory's vector as a base (average would be ideal but this is simpler).
	vec, _ := g.eng.VGet(indexName, relevantIDs[0])
	avgVec := make([]float32, len(vec.Vector))
	for _, id := range relevantIDs {
		d, err := g.eng.VGet(indexName, id)
		if err != nil || len(d.Vector) != len(avgVec) {
			continue
		}
		for j, v := range d.Vector {
			avgVec[j] += v
		}
	}
	for j := range avgVec {
		avgVec[j] /= float32(len(relevantIDs))
	}

	confidence := math.Min(1.0, float64(len(promptLines))/10.0)

	meta := map[string]any{
		"type":                "user_profile_insight",
		"content":             aiResp.Recommendation,
		"preferences":         aiResp.PreferencesDiscovered,
		"status":              "active",
		"confidence":          confidence,
		"source_memory_count": float64(len(relevantIDs)),
		"_created_at":         float64(time.Now().Unix()),
	}

	if err := g.eng.VAdd(indexName, insightID, avgVec, meta); err != nil {
		slog.Error("[Cognitive Engine] Failed to save user profile insight", "error", err)
		return
	}

	// Link to source memories.
	for _, srcID := range relevantIDs {
		if err := g.eng.VLink(indexName, insightID, srcID, "derived_from_interactions", "interaction_of", 1.0, nil); err != nil {
			slog.Warn("[Cognitive Engine] Failed to link user preference", "error", err)
		}
	}

	slog.Info("[Cognitive Engine] User profile insight created.",
		"insight_id", insightID,
		"preferences_count", len(aiResp.PreferencesDiscovered),
		"source_memories", len(relevantIDs))
}

// detectSentimentShifts compares past vs recent sentiment for an entity
// and detects opinion reversals over a 2-week window.
func (g *Gardener) detectSentimentShifts(indexName string, lang string) {
	lex, ok := sentimentLexicons[lang]
	if !ok {
		return // Unsupported language — skip sentiment analysis.
	}

	currentCursor := g.scanCursors[indexName+"_sentiment"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_sentiment"] = nextCursor

	now := time.Now().UnixNano()
	twoWeeksAgo := now - (14 * 24 * int64(time.Hour))

	for _, id := range ids {
		edges, found := g.eng.VGetIncomingEdges(indexName, id, "mentions", 0)
		if !found || len(edges) < 4 {
			continue // Not enough memories to establish a pattern.
		}

		var pastScore, recentScore float64
		var pastCount, recentCount int

		for _, edge := range edges {
			// Note: edge.TargetID is the source node for incoming edges.
			sourceData, err := g.eng.VGet(indexName, edge.TargetID)
			if err != nil {
				continue
			}

			content, ok := sourceData.Metadata["content"].(string)
			if !ok {
				continue
			}

			content = strings.ToLower(content)
			score := 0.0
			for _, w := range lex.Positive {
				if strings.Contains(content, w) {
					score += 1.0
				}
			}
			for _, w := range lex.Negative {
				if strings.Contains(content, w) {
					score -= 1.0
				}
			}

			if edge.CreatedAt < twoWeeksAgo {
				pastScore += score
				pastCount++
			} else {
				recentScore += score
				recentCount++
			}
		}

		if pastCount > 0 && recentCount > 0 {
			avgPast := pastScore / float64(pastCount)
			avgRecent := recentScore / float64(recentCount)
			delta := avgRecent - avgPast

			// Strong sentiment shift detected (e.g., negative to positive).
			if math.Abs(delta) >= 1.5 {
				links, found := g.eng.VGetLinks(indexName, id, "sentiment_analyzed")
				if found && len(links) > 0 {
					continue
				}

				if err := g.eng.VLink(indexName, id, id, "sentiment_analyzed", "", 1.0, nil); err != nil { // Self-link as dedup marker
					slog.Warn("[Cognitive Engine] Failed to mark sentiment as analyzed", "error", err)
					continue
				}

				direction := "positive"
				if delta < 0 {
					direction = "negative"
				}

				slog.Info("[Cognitive Engine] 🎭 Sentiment Shift Detected!", "entity", id, "shift", direction)

				nodeData, _ := g.eng.VGet(indexName, id)
				reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())
				evidenceRatio := math.Min(1.0, float64(pastCount+recentCount)/8.0)
				confidence := math.Min(1.0, (math.Abs(delta)/3.0)*evidenceRatio)
				meta := map[string]any{
					"type":        "reflection",
					"content":     fmt.Sprintf("Sentiment shift detected for '%s'. Opinion has evolved in a heavily %s direction over the last 2 weeks.", id, direction),
					"status":      "insight",
					"confidence":  confidence,
					"_created_at": float64(time.Now().Unix()),
				}
				g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
				if err := g.eng.VLink(indexName, reflectionID, id, "sentiment_shift", "sentiment_shifted_by", 1.0, nil); err != nil {
					slog.Warn("[Cognitive Engine] Failed to link sentiment shift", "error", err)
				}
			}
		}
	}
}

// detectCentralityShifts detects nodes whose degree centrality has tripled
// in the last 30 days using time-travel graph queries.
func (g *Gardener) detectCentralityShifts(indexName string) {
	currentCursor := g.scanCursors[indexName+"_centrality"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_centrality"] = nextCursor

	now := time.Now().UnixNano()
	oneMonthAgo := now - (30 * 24 * int64(time.Hour))

	for _, id := range ids {
		// Current degree centrality.
		outRelsNow := g.eng.VGetRelations(indexName, id)
		inRelsNow := g.eng.VGetIncomingRelations(indexName, id)
		degreeNow := 0
		for _, targets := range outRelsNow {
			degreeNow += len(targets)
		}
		for _, sources := range inRelsNow {
			degreeNow += len(sources)
		}

		// Skip low-connectivity nodes.
		if degreeNow < 10 {
			continue
		}

		// Degree centrality 30 days ago (time-travel query).
		degreePast := 0
		for rel := range outRelsNow {
			if edges, found := g.eng.VGetEdges(indexName, id, rel, oneMonthAgo); found {
				degreePast += len(edges)
			}
		}
		for rel := range inRelsNow {
			if edges, found := g.eng.VGetIncomingEdges(indexName, id, rel, oneMonthAgo); found {
				degreePast += len(edges)
			}
		}

		// Centrality has more than tripled.
		if degreePast > 0 && float64(degreeNow) > float64(degreePast)*3.0 {
			links, found := g.eng.VGetLinks(indexName, id, "centrality_analyzed")
			if found && len(links) > 0 {
				continue
			}
			if err := g.eng.VLink(indexName, id, id, "centrality_analyzed", "", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to mark centrality as analyzed", "error", err)
				continue
			}

			slog.Info("[Cognitive Engine] 🕸️ Centrality Explosion Detected!", "entity", id, "growth", degreeNow-degreePast)

			nodeData, _ := g.eng.VGet(indexName, id)
			reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())
			confidence := math.Min(1.0, float64(degreeNow)/float64(degreePast)/5.0)
			meta := map[string]any{
				"type":        "reflection",
				"content":     fmt.Sprintf("Graph Centrality Shift: '%s' has become a core concept in the knowledge base, growing from %d to %d connections in 30 days.", id, degreePast, degreeNow),
				"status":      "insight",
				"confidence":  confidence,
				"_created_at": float64(time.Now().Unix()),
			}
			g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
			if err := g.eng.VLink(indexName, reflectionID, id, "became_central", "centralized_by", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to link centrality shift", "error", err)
			}
		}
	}
}

// detectForgettingPatterns finds historically important entities that have been
// abandoned for over 30 days.
func (g *Gardener) detectForgettingPatterns(indexName string) {
	currentCursor := g.scanCursors[indexName+"_forgetting"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 200)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_forgetting"] = nextCursor

	now := time.Now().UnixNano()
	oneMonthAgo := now - (30 * 24 * int64(time.Hour))

	for _, id := range ids {
		edges, found := g.eng.VGetIncomingEdges(indexName, id, "mentions", 0)
		if !found || len(edges) < 5 {
			continue // Never significant enough to track.
		}

		recentActivity := false
		for _, edge := range edges {
			if edge.CreatedAt > oneMonthAgo {
				recentActivity = true
				break
			}
		}

		if !recentActivity {
			// Deduplicazione
			links, found := g.eng.VGetLinks(indexName, id, "decay_analyzed")
			if found && len(links) > 0 {
				continue
			}
			if err := g.eng.VLink(indexName, id, id, "decay_analyzed", "", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to mark decay as analyzed", "error", err)
				continue
			}

			slog.Info("[Cognitive Engine] 🍂 Knowledge Decay Detected!", "entity", id)

			nodeData, _ := g.eng.VGet(indexName, id)
			reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())
			confidence := math.Min(1.0, float64(len(edges))/10.0)
			meta := map[string]any{
				"type":        "reflection",
				"content":     fmt.Sprintf("Knowledge Decay: The concept '%s' was previously important (%d mentions) but hasn't been accessed or mentioned in over 30 days.", id, len(edges)),
				"status":      "insight",
				"confidence":  confidence,
				"_created_at": float64(time.Now().Unix()),
			}
			g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
			if err := g.eng.VLink(indexName, reflectionID, id, "knowledge_decay", "decaying_in", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to link knowledge decay", "error", err)
			}
		}
	}
}

// detectRepeatedFailures scans for agent actions that have failed repeatedly
// and uses the LLM to diagnose the root cause and suggest a fix.
func (g *Gardener) detectRepeatedFailures(indexName string) {
	now := time.Now()
	twentyFourHoursAgo := now.Add(-24 * time.Hour)
	minTimestamp := float64(twentyFourHoursAgo.Unix())

	// Use VFilter to efficiently find recent failed agent actions.
	filter := "type='agent_action' AND status='failed'"
	ids, err := g.eng.VFilter(indexName, filter, 500)
	if err != nil || len(ids) < 3 {
		return
	}

	nodes, _ := g.eng.VGetMany(indexName, ids)

	// Group failures by action, filtering to last 24h.
	type failureGroup struct {
		action string
		nodes  []core.VectorData
	}
	groups := make(map[string]*failureGroup)

	for _, node := range nodes {
		// Time filter: only consider failures from the last 24 hours.
		if ts, ok := node.Metadata["_created_at"].(float64); ok && ts < minTimestamp {
			continue
		}

		action, _ := node.Metadata["action"].(string)
		if action == "" {
			action = "unknown"
		}

		if _, exists := groups[action]; !exists {
			groups[action] = &failureGroup{action: action}
		}
		groups[action].nodes = append(groups[action].nodes, node)
	}

	for _, group := range groups {
		if len(group.nodes) < 3 {
			continue // Need at least 3 failures to detect a pattern.
		}

		// Dedup: check if any failure node in this group was already analyzed.
		alreadyAnalyzed := false
		for _, n := range group.nodes {
			existingLinks, found := g.eng.VGetLinks(indexName, n.ID, "failure_analyzed")
			if found && len(existingLinks) > 0 {
				alreadyAnalyzed = true
				break
			}
		}
		if alreadyAnalyzed {
			continue
		}

		// Mark the first node as analyzed.
		if err := g.eng.VLink(indexName, group.nodes[0].ID, group.nodes[0].ID, "failure_analyzed", "", 1.0, nil); err != nil {
			slog.Warn("[Cognitive Engine] Failed to mark failure as analyzed", "error", err)
			continue
		}

		// Build prompt with timestamps.
		var promptLines []string
		for _, n := range group.nodes {
			content, _ := n.Metadata["content"].(string)
			dateStr := "unknown"
			if ts, ok := n.Metadata["_created_at"].(float64); ok {
				dateStr = time.Unix(int64(ts), 0).Format("2006-01-02 15:04")
			}
			promptLines = append(promptLines, fmt.Sprintf("- [%s] %s", dateStr, content))
		}

		sysPrompt := `You are a debugging analyst for an AI agent. The agent has been repeatedly failing at the same action. Analyze the failure logs and identify the pattern.
Return ONLY a valid JSON object:
{"pattern": "...", "root_cause": "...", "recommendation": "...", "severity": "low|medium|high"}

Guidelines:
- pattern: concise description of what's going wrong
- root_cause: the underlying reason
- recommendation: specific fix the agent should apply
- severity: "high" if agent is completely blocked, "medium" if degraded, "low" if intermittent`

		userPrompt := fmt.Sprintf("Repeated failures for action \"%s\" (%d failures in last 24h):\n%s",
			group.action, len(group.nodes), strings.Join(promptLines, "\n"))

		slog.Info("[Cognitive Engine] Analyzing repeated failures...", "action", group.action, "count", len(group.nodes))

		respText, err := g.llm.Chat(sysPrompt, userPrompt)
		if err != nil {
			continue
		}

		startIdx := strings.Index(respText, "{")
		endIdx := strings.LastIndex(respText, "}")
		if startIdx != -1 && endIdx != -1 && endIdx > startIdx {
			respText = respText[startIdx : endIdx+1]
		}

		var aiResp llmFailurePatternResponse
		if err := json.Unmarshal([]byte(respText), &aiResp); err != nil {
			continue
		}

		if aiResp.Pattern == "" {
			continue
		}

		// Create failure_pattern node.
		patternID := fmt.Sprintf("failure_pattern_%d", time.Now().UnixNano())

		// Average vector from source failures.
		dim := len(group.nodes[0].Vector)
		avgVec := make([]float32, dim)
		for _, n := range group.nodes {
			if len(n.Vector) == dim {
				for j, v := range n.Vector {
					avgVec[j] += v
				}
			}
		}
		for j := range avgVec {
			avgVec[j] /= float32(len(group.nodes))
		}

		confidence := math.Min(1.0, float64(len(group.nodes))/10.0)

		meta := map[string]any{
			"type":          "failure_pattern",
			"content":       aiResp.Recommendation,
			"pattern":       aiResp.Pattern,
			"root_cause":    aiResp.RootCause,
			"severity":      aiResp.Severity,
			"status":        "unresolved",
			"confidence":    confidence,
			"failure_count": float64(len(group.nodes)),
			"_created_at":   float64(time.Now().Unix()),
		}

		if err := g.eng.VAdd(indexName, patternID, avgVec, meta); err != nil {
			slog.Error("[Cognitive Engine] Failed to save failure pattern", "error", err)
			continue
		}

		for _, n := range group.nodes {
			if err := g.eng.VLink(indexName, patternID, n.ID, "failure_pattern_of", "has_failure_pattern", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to link failure pattern", "error", err)
			}
		}

		slog.Info("[Cognitive Engine] Failure pattern detected!",
			"action", group.action,
			"pattern", aiResp.Pattern,
			"severity", aiResp.Severity)
	}
}

// detectKnowledgeEvolution analyzes how an entity's knowledge neighborhood has evolved
// over time using VExtractSubgraph time-travel snapshots at 3 points in time.
func (g *Gardener) detectKnowledgeEvolution(indexName string) {
	currentCursor := g.scanCursors[indexName+"_evolution"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_evolution"] = nextCursor

	now := time.Now()
	oneDayAgo := now.Add(-24 * time.Hour).UnixNano()
	fifteenDaysAgo := now.Add(-15 * 24 * time.Hour).UnixNano()
	thirtyDaysAgo := now.Add(-30 * 24 * time.Hour).UnixNano()

	relations := []string{"mentions", "related_to", "about", "suggests_link", "consolidated_into", "derived_from"}

	processed := 0
	for _, id := range ids {
		if processed >= 3 {
			break // Limit to 3 entities per cycle to control cost.
		}

		// Only analyze high-centrality entities.
		inRels := g.eng.VGetIncomingRelations(indexName, id)
		inDegree := 0
		for _, sources := range inRels {
			inDegree += len(sources)
		}
		if inDegree < 15 {
			continue
		}

		// Must be an entity type.
		nodeData, err := g.eng.VGet(indexName, id)
		if err != nil {
			continue
		}
		nodeType, _ := nodeData.Metadata["type"].(string)
		if nodeType != "entity" {
			continue
		}

		// Dedup: skip if already analyzed.
		existingLinks, found := g.eng.VGetLinks(indexName, id, "evolution_analyzed")
		if found && len(existingLinks) > 0 {
			continue
		}

		// Mark as analyzed.
		if err := g.eng.VLink(indexName, id, id, "evolution_analyzed", "", 1.0, nil); err != nil {
			slog.Warn("[Cognitive Engine] Failed to mark entity as evolution-analyzed", "error", err)
			continue
		}

		// Extract 3 subgraph snapshots via time travel.
		subgraphPast, _ := g.eng.VExtractSubgraph(indexName, id, relations, 2, thirtyDaysAgo, nil, 0)
		subgraphMid, _ := g.eng.VExtractSubgraph(indexName, id, relations, 2, fifteenDaysAgo, nil, 0)
		subgraphNow, _ := g.eng.VExtractSubgraph(indexName, id, relations, 2, oneDayAgo, nil, 0)

		// Get topic name.
		topicName := id
		if name, ok := nodeData.Metadata["name"].(string); ok && name != "" {
			topicName = name
		}

		// Format subgraphs as readable text for the LLM.
		formatSnapshot := func(label string, sg *engine.SubgraphResult) string {
			if sg == nil || len(sg.Nodes) <= 1 {
				return fmt.Sprintf("%s: No connected knowledge yet.", label)
			}
			nodeNames := []string{}
			for _, n := range sg.Nodes {
				if n.ID == sg.RootID {
					continue
				}
				name := n.ID
				if nodeName, ok := n.Metadata["name"].(string); ok && nodeName != "" {
					name = nodeName
				} else if c, ok := n.Metadata["content"].(string); ok && len(c) > 50 {
					name = c[:50] + "..."
				}
				nodeNames = append(nodeNames, name)
			}
			return fmt.Sprintf("%s: %d connected nodes — %s", label, len(nodeNames), strings.Join(nodeNames, ", "))
		}

		snapshotText := fmt.Sprintf("Topic: %s\n%s\n%s\n%s",
			topicName,
			formatSnapshot("30 days ago", subgraphPast),
			formatSnapshot("15 days ago", subgraphMid),
			formatSnapshot("Today", subgraphNow),
		)

		sysPrompt := `You are a knowledge evolution analyst for an AI agent. You are given 3 snapshots of what the agent knew about a specific topic at 3 different points in time. Analyze how the agent's understanding evolved and identify what's still missing.
Return ONLY a valid JSON object:
{"timeline": "...", "competency_level": "beginner|intermediate|advanced|expert", "knowledge_gaps": ["gap1", "gap2"], "next_steps": "..."}

Guidelines:
- timeline: describe the evolution in 3 phases
- competency_level: rate the agent's current knowledge depth
- knowledge_gaps: list specific topics the agent should study next
- next_steps: concrete recommendation for what to learn/do next`

		slog.Info("[Cognitive Engine] Analyzing knowledge evolution...", "entity", topicName, "in_degree", inDegree)

		respText, err := g.llm.Chat(sysPrompt, snapshotText)
		if err != nil {
			continue
		}

		startIdx := strings.Index(respText, "{")
		endIdx := strings.LastIndex(respText, "}")
		if startIdx != -1 && endIdx != -1 && endIdx > startIdx {
			respText = respText[startIdx : endIdx+1]
		}

		var aiResp llmEvolutionResponse
		if err := json.Unmarshal([]byte(respText), &aiResp); err != nil {
			continue
		}

		if aiResp.Timeline == "" {
			continue
		}

		// Create knowledge_evolution node.
		evoID := fmt.Sprintf("knowledge_evolution_%d", time.Now().UnixNano())

		confidence := math.Min(1.0, float64(inDegree)/20.0)

		meta := map[string]any{
			"type":             "knowledge_evolution",
			"content":          aiResp.NextSteps,
			"topic":            topicName,
			"timeline":         aiResp.Timeline,
			"competency_level": aiResp.CompetencyLevel,
			"status":           "active",
			"confidence":       confidence,
			"_created_at":      float64(time.Now().Unix()),
		}

		if len(aiResp.KnowledgeGaps) > 0 {
			gapAnys := make([]any, len(aiResp.KnowledgeGaps))
			for i, g := range aiResp.KnowledgeGaps {
				gapAnys[i] = g
			}
			meta["knowledge_gaps"] = gapAnys
		}

		if err := g.eng.VAdd(indexName, evoID, nodeData.Vector, meta); err != nil {
			slog.Error("[Cognitive Engine] Failed to save knowledge evolution", "error", err)
			continue
		}

		if err := g.eng.VLink(indexName, evoID, id, "evolution_of", "evolved_by", 1.0, nil); err != nil {
			slog.Warn("[Cognitive Engine] Failed to link knowledge evolution", "error", err)
		}

		slog.Info("[Cognitive Engine] Knowledge evolution tracked.",
			"topic", topicName,
			"competency", aiResp.CompetencyLevel,
			"gaps_count", len(aiResp.KnowledgeGaps))

		processed++
	}
}
