// Package cognitive provides autonomous background processes for memory consolidation,
// contradiction detection, and meta-knowledge generation (Reflection Engine).
package cognitive

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"math"
	"strings"
	"time"

	"github.com/sanonone/kektordb/pkg/engine"
	"github.com/sanonone/kektordb/pkg/llm"
)

// ReflectionType categorizes the insights generated by the Gardener.
type ReflectionType string

const (
	TypeConsolidation ReflectionType = "consolidation" // Merged redundant memories
	TypeContradiction ReflectionType = "contradiction" // Detected conflicting facts
	TypeImportance    ReflectionType = "importance"    // Importance shift
)

// Reflection defines the schema for a meta-memory node.
// These will be stored in the DB with kind="reflection" and linked to original memories.
type Reflection struct {
	Type        ReflectionType `json:"type"`
	Content     string         `json:"content"`
	Confidence  float64        `json:"confidence"`
	Status      string         `json:"status"`       // e.g., "resolved", "unresolved"
	DerivedFrom []string       `json:"derived_from"` // Original memory IDs
}

// Config holds the scheduling and AI settings for the cognitive engine.
type Config struct {
	Enabled       bool
	Interval      time.Duration
	Mode          string   // "basic" (No LLM), "advanced" (Uses LLM)
	TargetIndexes []string // ["*"] for all, or["mcp_memory", "tenant_A"]
}

// Gardener is the autonomous background worker that analyzes the database graph
// to consolidate memories and generate reflections.
type Gardener struct {
	eng         *engine.Engine
	llm         llm.Client // LLM client for synthesis and reasoning
	cfg         Config
	stopCh      chan struct{}
	scanCursors map[string]uint32 // Remember where we left off for each Namespace
}

type llmContradictionResponse struct {
	Contradiction bool   `json:"contradiction"`
	Reason        string `json:"reason"`
}

// NewGardener initializes the cognitive engine.
func NewGardener(eng *engine.Engine, llmClient llm.Client, cfg Config) *Gardener {
	if cfg.Interval == 0 {
		cfg.Interval = 10 * time.Minute // Default: think every 10 minutes
	}
	return &Gardener{
		eng:         eng,
		llm:         llmClient,
		cfg:         cfg,
		stopCh:      make(chan struct{}),
		scanCursors: make(map[string]uint32),
	}
}

// Start launches the Gardener's background loop.
func (g *Gardener) Start() {
	if !g.cfg.Enabled {
		return
	}
	slog.Info("[Cognitive Engine] Gardener started. Sleep cycle initiated.", "interval", g.cfg.Interval)
	go g.loop()
}

// Stop gracefully halts the cognitive engine.
func (g *Gardener) Stop() {
	if !g.cfg.Enabled {
		return
	}
	close(g.stopCh)
	slog.Info("[Cognitive Engine] Gardener stopped.")
}

func (g *Gardener) loop() {
	ticker := time.NewTicker(g.cfg.Interval)
	defer ticker.Stop()

	for {
		select {
		case <-g.stopCh:
			return
		case <-ticker.C:
			g.think()
		}
	}
}

// isIndexAllowed checks whether this index is in the Gardener's target list.
func (c *Config) isIndexAllowed(indexName string) bool {
	if len(c.TargetIndexes) == 0 {
		return false
	}
	for _, target := range c.TargetIndexes {
		if target == "*" || target == indexName {
			return true
		}
	}
	return false
}

// think is the main entry point for the "REM Sleep" phase of the database.
func (g *Gardener) think() {
	slog.Info("[Cognitive Engine] Gardener is waking up... scanning all active namespaces.")

	indexInfos, err := g.eng.DB.GetVectorIndexInfoAPI()
	if err != nil || len(indexInfos) == 0 {
		return
	}

	for _, info := range indexInfos {
		idx := info.Name

		// 1. Skip indexes not in the target list.
		if !g.cfg.isIndexAllowed(idx) {
			continue
		}

		// 2. Skip indexes with too few vectors to produce meaningful clusters.
		if info.VectorCount < 10 {
			continue
		}

		slog.Debug("[Cognitive Engine] Analyzing namespace", "index", idx, "mode", g.cfg.Mode)

		// =====================================================================
		// LAYER 1: BASIC (Fast, Math & Graph Only, NO LLM)
		// Always active when enabled. CPU cost: low.
		// =====================================================================

		g.detectKnowledgeGaps(idx)
		g.detectImportanceShifts(idx)
		g.detectSentimentShifts(idx)
		g.detectCentralityShifts(idx)
		g.detectForgettingPatterns(idx)

		// =====================================================================
		// LAYER 2: ADVANCED & META (Slow, LLM Required)
		// Active only when Mode is "advanced" or "meta" and an LLM client is configured.
		// =====================================================================

		if g.cfg.Mode == "advanced" || g.cfg.Mode == "meta" {
			if g.llm != nil {
				// 1. Consolidation
				clusters := g.findRedundantClusters(idx, 0.90, 5)
				for _, cluster := range clusters {
					g.consolidateCluster(idx, cluster)
				}

				// 2. Contradiction detection
				g.detectContradictions(idx)
			} else {
				slog.Warn("[Cognitive Engine] Advanced mode requested but no LLM client provided. Skipping deep reflections.", "index", idx)
			}
		}
	}

	slog.Info("[Cognitive Engine] Sleep cycle completed. Graph optimized.")

}

// MemoryCluster represents a group of highly similar memories.
type MemoryCluster struct {
	CenterID  string
	MemberIDs []string
}

func (g *Gardener) findRedundantClusters(indexName string, similarityThreshold float64, minClusterSize int) []MemoryCluster {
	currentCursor := g.scanCursors[indexName]

	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 500)
	if err != nil || len(ids) == 0 {
		return nil
	}
	g.scanCursors[indexName] = nextCursor

	vectorDataList, err := g.eng.VGetMany(indexName, ids)
	if err != nil {
		return nil
	}

	var clusters []MemoryCluster
	clusteredSet := make(map[string]struct{})

	for _, vData := range vectorDataList {
		if _, alreadyClustered := clusteredSet[vData.ID]; alreadyClustered {
			continue
		}

		// Skip archived memories and meta-nodes (master/reflections).
		if archived, ok := vData.Metadata["_archived"].(bool); ok && archived {
			continue
		}
		if memType, ok := vData.Metadata["type"].(string); ok && (memType == "consolidated_memory" || memType == "reflection") {
			continue
		}

		results, err := g.eng.VSearchWithScores(indexName, vData.Vector, 10)
		if err != nil {
			continue
		}

		var currentCluster []string
		for _, res := range results {
			if res.Score >= similarityThreshold {
				if _, seen := clusteredSet[res.ID]; !seen {
					// Also skip archived or meta-type neighbors.
					neighborData, err := g.eng.VGet(indexName, res.ID)
					if err == nil {
						if arch, ok := neighborData.Metadata["_archived"].(bool); ok && arch {
							continue
						}
						if memType, ok := neighborData.Metadata["type"].(string); ok && (memType == "consolidated_memory" || memType == "reflection") {
							continue
						}

						currentCluster = append(currentCluster, res.ID)
						clusteredSet[res.ID] = struct{}{}
					}
				}
			}
		}

		if len(currentCluster) >= minClusterSize {
			clusters = append(clusters, MemoryCluster{
				CenterID:  vData.ID,
				MemberIDs: currentCluster,
			})
		}
	}

	return clusters
}

// consolidateCluster sends redundant memories to the LLM for synthesis, creates a Master Memory,
// and archives the original memories by linking them via the graph.
func (g *Gardener) consolidateCluster(indexName string, cluster MemoryCluster) {
	// 1. Fetch data for all memories in the cluster
	items, err := g.eng.VGetMany(indexName, cluster.MemberIDs)
	if err != nil || len(items) == 0 {
		return
	}

	// 2. Prepare text and compute the Average Vector (Zero-Cost Embedding!)
	var texts []string
	dim := len(items[0].Vector)
	avgVector := make([]float32, dim)

	maxItemsForLLM := 15

	for i, item := range items {
		content := ""
		if val, ok := item.Metadata["content"]; ok {
			content = fmt.Sprintf("%v", val)
		}

		if i < maxItemsForLLM {
			texts = append(texts, fmt.Sprintf("- %s", content))
		}

		// Sum all vectors in the cluster (not just the LLM subset) to compute a precise average.
		if len(item.Vector) == dim {
			for j, v := range item.Vector {
				avgVector[j] += v
			}
		}
	}

	// Vector Average
	for i := range avgVector {
		avgVector[i] /= float32(len(items))
	}

	// 3. LLM Synthesis (The Cognitive Phase)
	sysPrompt := "You are a cognitive memory consolidator for an AI agent. Read the following redundant memory snippets and synthesize them into a single, comprehensive, and clear memory/fact. Keep it concise but retain all key information. Return ONLY the synthesized text, nothing else."
	userPrompt := strings.Join(texts, "\n")

	slog.Info("[Cognitive Engine] Asking LLM to synthesize memories...", "cluster_size", len(items))

	summary, err := g.llm.Chat(sysPrompt, userPrompt)
	if err != nil || summary == "" {
		slog.Warn("[Cognitive Engine] LLM synthesis failed", "error", err)
		return
	}

	// Clean up potential markdown formatting from LLM
	summary = strings.TrimSpace(strings.TrimPrefix(strings.TrimSuffix(summary, "```"), "```"))

	// 4. Save Master Memory to DB
	masterID := fmt.Sprintf("consolidation_%d", time.Now().UnixNano())
	masterMeta := map[string]any{
		"content":            summary,
		"type":               "consolidated_memory",
		"_created_at":        float64(time.Now().Unix()),
		"derived_from_count": float64(len(items)),
	}

	err = g.eng.VAdd(indexName, masterID, avgVector, masterMeta)
	if err != nil {
		slog.Error("[Cognitive Engine] Failed to save master memory", "error", err)
		return
	}

	// 5. Update and Link old memories (Archive them)
	for _, item := range items {
		// Link: old memory --[consolidated_into]--> master memory
		if err := g.eng.VLink(indexName, item.ID, masterID, "consolidated_into", "derived_from", 1.0, nil); err != nil {
			slog.Warn("[Cognitive Engine] Failed to link consolidated memory", "from", item.ID, "error", err)
		}

		metaUpdate := map[string]any{
			"_archived":          true,
			"_consolidated_into": masterID,
		}
		if err := g.eng.VSetMetadata(indexName, item.ID, metaUpdate); err != nil {
			slog.Warn("[Cognitive Engine] Failed to archive memory", "id", item.ID, "error", err)
		}
	}

	slog.Info("[Cognitive Engine] Cluster successfully consolidated! 🧠",
		"master_id", masterID,
		"merged_count", len(items),
		"summary_preview", summary[:min(50, len(summary))]+"...")
}

// detectContradictions finds memories about the same topic that make conflicting claims.
func (g *Gardener) detectContradictions(indexName string) {
	// Small batch (50) because each pair triggers an LLM call.
	currentCursor := g.scanCursors[indexName+"_contradictions"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 50)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_contradictions"] = nextCursor

	nodes, _ := g.eng.VGetMany(indexName, ids)

	for _, node := range nodes {
		contentA, ok := node.Metadata["content"].(string)
		if !ok || contentA == "" {
			continue
		}

		// Find semantically similar but non-identical memories (score 0.70–0.95).
		neighbors, _ := g.eng.VSearchWithScores(indexName, node.Vector, 5)

		for _, neighbor := range neighbors {
			if neighbor.ID == node.ID || neighbor.Score > 0.95 || neighbor.Score < 0.70 {
				continue
			}

			// Dedup via graph edge: skip if this pair was already analyzed.
			existingLinks, found := g.eng.VGetLinks(indexName, node.ID, "analyzed_against")
			if found {
				skip := false
				for _, link := range existingLinks {
					if link == neighbor.ID {
						skip = true
						break
					}
				}
				if skip {
					continue
				}
			}

			// Mark the pair as analyzed to prevent re-processing.
			if err := g.eng.VLink(indexName, node.ID, neighbor.ID, "analyzed_against", "analyzed_against", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to mark pair as analyzed", "error", err)
				continue
			}

			neighborData, err := g.eng.VGet(indexName, neighbor.ID)
			if err != nil {
				continue
			}
			contentB, ok := neighborData.Metadata["content"].(string)
			if !ok {
				continue
			}

			// Ask the LLM for a contradiction analysis.
			sysPrompt := `Analyze the following two memory statements from an AI agent.
Do they logically contradict each other? (e.g., Statement A says the price is $10, B says it's $20).
Return ONLY a valid JSON object: {"contradiction": true/false, "reason": "brief explanation"}`

			userPrompt := fmt.Sprintf("Statement A: %s\nStatement B: %s", contentA, contentB)

			respText, err := g.llm.Chat(sysPrompt, userPrompt)
			if err != nil {
				continue
			}

			// Extract JSON from the response, stripping any markdown or extra text.
			startIdx := strings.Index(respText, "{")
			endIdx := strings.LastIndex(respText, "}")
			if startIdx != -1 && endIdx != -1 && endIdx > startIdx {
				respText = respText[startIdx : endIdx+1]
			}

			var aiAnalysis llmContradictionResponse
			if err := json.Unmarshal([]byte(respText), &aiAnalysis); err == nil {
				if aiAnalysis.Contradiction {
					slog.Info("[Cognitive Engine] ⚠️ Contradiction Detected!", "reason", aiAnalysis.Reason)

					reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())

					// Zero-cost embedding: average of the two conflicting vectors.
					dim := len(node.Vector)
					avgVec := make([]float32, dim)
					for i := range node.Vector {
						avgVec[i] = (node.Vector[i] + neighborData.Vector[i]) / 2.0
					}

					meta := map[string]any{
						"type":        "reflection",
						"content":     fmt.Sprintf("Conflict detected: %s", aiAnalysis.Reason),
						"status":      "unresolved",
						"_created_at": float64(time.Now().Unix()),
					}

					g.eng.VAdd(indexName, reflectionID, avgVec, meta)

					// Link both memories to the reflection node.
					if err := g.eng.VLink(indexName, reflectionID, node.ID, "contradicts", "contradicted_by", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link contradiction", "error", err)
					}
					if err := g.eng.VLink(indexName, reflectionID, neighbor.ID, "contradicts", "contradicted_by", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link contradiction", "error", err)
					}
				}
			}
		}
	}
}

// detectImportanceShifts detects entities that have suddenly become popular
// by comparing edge timestamps over the last 3 days.
func (g *Gardener) detectImportanceShifts(indexName string) {
	currentCursor := g.scanCursors[indexName+"_shifts"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 200)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_shifts"] = nextCursor

	now := time.Now().UnixNano()
	threeDaysAgo := now - (3 * 24 * int64(time.Hour))

	for _, id := range ids {
		edges, found := g.eng.VGetIncomingEdges(indexName, id, "mentions", 0)
		if !found || len(edges) < 5 {
			continue // Too few links to be significant.
		}

		recentMentions := 0
		oldMentions := 0

		// Count when edges were created (time-travel query).
		for _, edge := range edges {
			if edge.CreatedAt > threeDaysAgo {
				recentMentions++
			} else {
				oldMentions++
			}
		}

		// Spike heuristic: more mentions in the last 3 days than in all prior history.
		if recentMentions > 5 && recentMentions > (oldMentions*2) {
			slog.Info("[Cognitive Engine] 📈 Importance Shift Detected!", "entity", id, "recent_mentions", recentMentions)

			// Anti-spam: skip if a reflection already exists for this entity.
			alreadyFlagged := false
			if existingRefs, ok := g.eng.VGetIncoming(indexName, id, "focus_shifted"); ok {
				if len(existingRefs) > 0 {
					alreadyFlagged = true
				}
			}

			if !alreadyFlagged {
				reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())

				nodeData, _ := g.eng.VGet(indexName, id)

				meta := map[string]any{
					"type":        "reflection",
					"content":     fmt.Sprintf("Sudden surge of interest in '%s'. Received %d new mentions recently.", id, recentMentions),
					"status":      "insight",
					"_created_at": float64(time.Now().Unix()),
				}

				g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
				if err := g.eng.VLink(indexName, reflectionID, id, "focus_shifted", "focus_shifted_by", 1.0, nil); err != nil {
					slog.Warn("[Cognitive Engine] Failed to link importance shift", "error", err)
				}
			}
		}
	}
}

// ForceThink triggers a cognitive cycle immediately for a specific index.
// Used by the HTTP API for manual intervention or after heavy bulk imports.
func (g *Gardener) ForceThink(indexName string) {
	if !g.eng.IndexExists(indexName) {
		slog.Warn("[Cognitive Engine] Cannot think on missing index", "index", indexName)
		return
	}

	// Security check: verify index is in the target list.
	if !g.cfg.isIndexAllowed(indexName) {
		slog.Warn("[Cognitive Engine] Index not in target list for cognitive analysis", "index", indexName)
		return
	}

	slog.Info("[Cognitive Engine] Manual reflection cycle triggered.", "index", indexName, "mode", g.cfg.Mode)

	// =====================================================================
	// LAYER 1: BASIC (Fast, Math & Graph Only, NO LLM)
	// =====================================================================
	g.detectKnowledgeGaps(indexName)
	g.detectImportanceShifts(indexName)
	g.detectSentimentShifts(indexName)
	g.detectCentralityShifts(indexName)
	g.detectForgettingPatterns(indexName)

	// =====================================================================
	// LAYER 2: ADVANCED & META (Slow, LLM Required)
	// =====================================================================
	if g.cfg.Mode == "advanced" || g.cfg.Mode == "meta" {
		if g.llm != nil {
			// 1. Consolidation
			clusters := g.findRedundantClusters(indexName, 0.90, 5)
			for _, cluster := range clusters {
				g.consolidateCluster(indexName, cluster)
			}

			// 2. Contradiction detection
			g.detectContradictions(indexName)
		} else {
			slog.Warn("[Cognitive Engine] Advanced mode requested but no LLM client provided. Skipping deep reflections.", "index", indexName)
		}
	}
}

// detectKnowledgeGaps finds concepts that are semantically very close but
// lack an explicit topological relationship in the graph.
func (g *Gardener) detectKnowledgeGaps(indexName string) {
	currentCursor := g.scanCursors[indexName+"_gaps"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_gaps"] = nextCursor

	nodes, _ := g.eng.VGetMany(indexName, ids)

	for _, node := range nodes {
		// Only analyze entities and documents; skip raw chunks to reduce noise.
		nodeType, ok := node.Metadata["type"].(string)
		if !ok || (nodeType != "entity" && nodeType != "document") {
			continue
		}

		// Pre-load all relations once (not per neighbor).
		outRels := g.eng.VGetRelations(indexName, node.ID)
		inRels := g.eng.VGetIncomingRelations(indexName, node.ID)

		// Find top-5 semantically similar nodes (score > 0.85).
		neighbors, _ := g.eng.VSearchWithScores(indexName, node.Vector, 5)

		for _, neighbor := range neighbors {
			if neighbor.ID == node.ID || neighbor.Score < 0.85 {
				continue
			}

			neighborData, err := g.eng.VGet(indexName, neighbor.ID)
			if err != nil {
				continue
			}
			nType, ok := neighborData.Metadata["type"].(string)
			if !ok || (nType != "entity" && nType != "document") {
				continue
			}

			// Check if a direct graph edge exists between the two nodes (both directions).
			connected := false

			// Outgoing edges (node -> neighbor)
			for _, targets := range outRels {
				for _, t := range targets {
					if t == neighbor.ID {
						connected = true
						break
					}
				}
				if connected {
					break
				}
			}

			// Incoming edges (neighbor -> node)
			if !connected {
				for _, sources := range inRels {
					for _, s := range sources {
						if s == neighbor.ID {
							connected = true
							break
						}
					}
					if connected {
						break
					}
				}
			}

			// 5. Gap found: semantically close but topologically disconnected.
			if !connected {
				slog.Info("[Cognitive Engine] 🧩 Knowledge Gap Detected!", "node_a", node.ID, "node_b", neighbor.ID)

				// Dedup: check if this pair was already flagged.
				existingLinks, found := g.eng.VGetLinks(indexName, node.ID, "gap_analyzed")
				skip := false
				if found {
					for _, link := range existingLinks {
						if link == neighbor.ID {
							skip = true
							break
						}
					}
				}

				if !skip {
					if err := g.eng.VLink(indexName, node.ID, neighbor.ID, "gap_analyzed", "gap_analyzed", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to mark gap as analyzed", "error", err)
						continue
					}

					reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())

					dim := len(node.Vector)
					avgVec := make([]float32, dim)
					for i := range node.Vector {
						avgVec[i] = (node.Vector[i] + neighborData.Vector[i]) / 2.0
					}

					nameA := node.Metadata["name"]
					if nameA == nil {
						nameA = node.ID
					}
					nameB := neighborData.Metadata["name"]
					if nameB == nil {
						nameB = neighbor.ID
					}

					meta := map[string]any{
						"type":        "reflection",
						"content":     fmt.Sprintf("Implicit relationship discovered: '%v' and '%v' share high semantic similarity (%.2f) but lack an explicit graph connection. Consider linking them.", nameA, nameB, neighbor.Score),
						"status":      "insight",
						"_created_at": float64(time.Now().Unix()),
					}

					g.eng.VAdd(indexName, reflectionID, avgVec, meta)
					if err := g.eng.VLink(indexName, reflectionID, node.ID, "suggests_link", "", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link knowledge gap", "error", err)
					}
					if err := g.eng.VLink(indexName, reflectionID, neighbor.ID, "suggests_link", "", 1.0, nil); err != nil {
						slog.Warn("[Cognitive Engine] Failed to link knowledge gap", "error", err)
					}
					g.eng.VLink(indexName, reflectionID, neighbor.ID, "suggests_link", "", 1.0, nil)
				}
			}
		}
	}
}

// detectSentimentShifts compares past vs recent sentiment for an entity
// and detects opinion reversals over a 2-week window.
func (g *Gardener) detectSentimentShifts(indexName string) {
	currentCursor := g.scanCursors[indexName+"_sentiment"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_sentiment"] = nextCursor

	now := time.Now().UnixNano()
	twoWeeksAgo := now - (14 * 24 * int64(time.Hour))

	positiveWords := []string{"love", "great", "excellent", "good", "amazing", "prefer", "best"}
	negativeWords := []string{"hate", "terrible", "bad", "frustrating", "slow", "worst", "disappointing"}

	for _, id := range ids {
		edges, found := g.eng.VGetIncomingEdges(indexName, id, "mentions", 0)
		if !found || len(edges) < 4 {
			continue // Not enough memories to establish a pattern.
		}

		var pastScore, recentScore float64
		var pastCount, recentCount int

		for _, edge := range edges {
			// Note: edge.TargetID is the source node for incoming edges.
			sourceData, err := g.eng.VGet(indexName, edge.TargetID)
			if err != nil {
				continue
			}

			content, ok := sourceData.Metadata["content"].(string)
			if !ok {
				continue
			}

			content = strings.ToLower(content)
			score := 0.0
			for _, w := range positiveWords {
				if strings.Contains(content, w) {
					score += 1.0
				}
			}
			for _, w := range negativeWords {
				if strings.Contains(content, w) {
					score -= 1.0
				}
			}

			if edge.CreatedAt < twoWeeksAgo {
				pastScore += score
				pastCount++
			} else {
				recentScore += score
				recentCount++
			}
		}

		if pastCount > 0 && recentCount > 0 {
			avgPast := pastScore / float64(pastCount)
			avgRecent := recentScore / float64(recentCount)
			delta := avgRecent - avgPast

			// Strong sentiment shift detected (e.g., negative to positive).
			if math.Abs(delta) >= 1.5 {
				links, found := g.eng.VGetLinks(indexName, id, "sentiment_analyzed")
				if found && len(links) > 0 {
					continue
				}

				if err := g.eng.VLink(indexName, id, id, "sentiment_analyzed", "", 1.0, nil); err != nil { // Self-link as dedup marker
					slog.Warn("[Cognitive Engine] Failed to mark sentiment as analyzed", "error", err)
					continue
				}

				direction := "positive"
				if delta < 0 {
					direction = "negative"
				}

				slog.Info("[Cognitive Engine] 🎭 Sentiment Shift Detected!", "entity", id, "shift", direction)

				nodeData, _ := g.eng.VGet(indexName, id)
				reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())
				meta := map[string]any{
					"type":        "reflection",
					"content":     fmt.Sprintf("Sentiment shift detected for '%s'. Opinion has evolved in a heavily %s direction over the last 2 weeks.", id, direction),
					"status":      "insight",
					"_created_at": float64(time.Now().Unix()),
				}
				g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
				if err := g.eng.VLink(indexName, reflectionID, id, "sentiment_shift", "sentiment_shifted_by", 1.0, nil); err != nil {
					slog.Warn("[Cognitive Engine] Failed to link sentiment shift", "error", err)
				}
			}
		}
	}
}

// detectCentralityShifts detects nodes whose degree centrality has tripled
// in the last 30 days using time-travel graph queries.
func (g *Gardener) detectCentralityShifts(indexName string) {
	currentCursor := g.scanCursors[indexName+"_centrality"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 100)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_centrality"] = nextCursor

	now := time.Now().UnixNano()
	oneMonthAgo := now - (30 * 24 * int64(time.Hour))

	for _, id := range ids {
		// Current degree centrality.
		outRelsNow := g.eng.VGetRelations(indexName, id)
		inRelsNow := g.eng.VGetIncomingRelations(indexName, id)
		degreeNow := 0
		for _, targets := range outRelsNow {
			degreeNow += len(targets)
		}
		for _, sources := range inRelsNow {
			degreeNow += len(sources)
		}

		// Skip low-connectivity nodes.
		if degreeNow < 10 {
			continue
		}

		// Degree centrality 30 days ago (time-travel query).
		degreePast := 0
		for rel := range outRelsNow {
			if edges, found := g.eng.VGetEdges(indexName, id, rel, oneMonthAgo); found {
				degreePast += len(edges)
			}
		}
		for rel := range inRelsNow {
			if edges, found := g.eng.VGetIncomingEdges(indexName, id, rel, oneMonthAgo); found {
				degreePast += len(edges)
			}
		}

		// Centrality has more than tripled.
		if degreePast > 0 && float64(degreeNow) > float64(degreePast)*3.0 {
			links, found := g.eng.VGetLinks(indexName, id, "centrality_analyzed")
			if found && len(links) > 0 {
				continue
			}
			if err := g.eng.VLink(indexName, id, id, "centrality_analyzed", "", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to mark centrality as analyzed", "error", err)
				continue
			}

			slog.Info("[Cognitive Engine] 🕸️ Centrality Explosion Detected!", "entity", id, "growth", degreeNow-degreePast)

			nodeData, _ := g.eng.VGet(indexName, id)
			reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())
			meta := map[string]any{
				"type":        "reflection",
				"content":     fmt.Sprintf("Graph Centrality Shift: '%s' has become a core concept in the knowledge base, growing from %d to %d connections in 30 days.", id, degreePast, degreeNow),
				"status":      "insight",
				"_created_at": float64(time.Now().Unix()),
			}
			g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
			if err := g.eng.VLink(indexName, reflectionID, id, "became_central", "centralized_by", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to link centrality shift", "error", err)
			}
		}
	}
}

// detectForgettingPatterns finds historically important entities that have been
// abandoned for over 30 days.
func (g *Gardener) detectForgettingPatterns(indexName string) {
	currentCursor := g.scanCursors[indexName+"_forgetting"]
	ids, nextCursor, err := g.eng.VGetIDsByCursor(indexName, currentCursor, 200)
	if err != nil || len(ids) == 0 {
		return
	}
	g.scanCursors[indexName+"_forgetting"] = nextCursor

	now := time.Now().UnixNano()
	oneMonthAgo := now - (30 * 24 * int64(time.Hour))

	for _, id := range ids {
		edges, found := g.eng.VGetIncomingEdges(indexName, id, "mentions", 0)
		if !found || len(edges) < 5 {
			continue // Never significant enough to track.
		}

		recentActivity := false
		for _, edge := range edges {
			if edge.CreatedAt > oneMonthAgo {
				recentActivity = true
				break
			}
		}

		if !recentActivity {
			links, found := g.eng.VGetLinks(indexName, id, "decay_analyzed")
			if found && len(links) > 0 {
				continue
			}
			if err := g.eng.VLink(indexName, id, id, "decay_analyzed", "", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to mark decay as analyzed", "error", err)
				continue
			}

			slog.Info("[Cognitive Engine] 🍂 Knowledge Decay Detected!", "entity", id)

			nodeData, _ := g.eng.VGet(indexName, id)
			reflectionID := fmt.Sprintf("reflection_%d", time.Now().UnixNano())
			meta := map[string]any{
				"type":        "reflection",
				"content":     fmt.Sprintf("Knowledge Decay: The concept '%s' was previously important (%d mentions) but hasn't been accessed or mentioned in over 30 days.", id, len(edges)),
				"status":      "insight",
				"_created_at": float64(time.Now().Unix()),
			}
			g.eng.VAdd(indexName, reflectionID, nodeData.Vector, meta)
			if err := g.eng.VLink(indexName, reflectionID, id, "knowledge_decay", "decaying_in", 1.0, nil); err != nil {
				slog.Warn("[Cognitive Engine] Failed to link knowledge decay", "error", err)
			}
		}
	}
}
